# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate aDDM process by unique trial condition (2 items)
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title Simulate aDDM process (by condition, 2 items)
#' \code{aevacc2_by_condition()}
#' @return vector that stores decisions and rts for each simulation run
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur maximum duration in ms that the process is allowed to simulate
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixation_model a user supplied fixation model that will be utilized to supply fixation locations and potentially fixation durations
#' @export
aevacc2_by_condition <- function(sd, theta, drift, non_decision_time, maxdur, update, fixation_model, nr_reps, timestep) {
    .Call('addmtoolbox_aevacc2_by_condition', PACKAGE = 'addmtoolbox', sd, theta, drift, non_decision_time, maxdur, update, fixation_model, nr_reps, timestep)
}

#' Simulate aDDM process by unique trial (2 items)
#' \code{aevacc2_by_trial()}
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title Simulate aDDM process (by trial, 2 items)
#' @return numeric variable that provides a success count (runs that predicted a reaction time in the correct rt-bin and simultaneously the correct decision)
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta (attentional bias) used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur numeric variable that supplies the maximum reaction time considered a success in simulations
#' @param mindur numeric variable that supplies the minimum reaction time considered a succes in simulations
#' @param cur_decision numeric variable that provides the empirical decision taken in trial
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixpos Vector that stores the locations for a supplied fixed fixation pathway
#' @param fixdur Vector that stores the fixation durations for a supplied fixed fixation pathway
#' @param cur_maxfix integer that provides number of fixation in trial
#' @export
aevacc2_by_trial <- function(sd, theta, drift, non_decision_time, maxdur, mindur, cur_decision, update, fixpos, fixdur, cur_maxfix, nr_reps, timestep) {
    .Call('addmtoolbox_aevacc2_by_trial', PACKAGE = 'addmtoolbox', sd, theta, drift, non_decision_time, maxdur, mindur, cur_decision, update, fixpos, fixdur, cur_maxfix, nr_reps, timestep)
}

#' Simulate aDDM process (2 items) with detailed output
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title Simulate aDDM process (2 items) with detailed output
#' \code{aevacc2_full_output()}
#' @return vector that stores detailed output by simulation run
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta (attentional bias) used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur maximum duration in ms that the process is allowed to simulate
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixation_model a user supplied fixation model that will be utilized to supply fixation locations and potentially fixation durations
#' @export
aevacc2_full_output <- function(sd, theta, drift, non_decision_time, maxdur, update, fixation_model, nr_reps, timestep) {
    .Call('addmtoolbox_aevacc2_full_output', PACKAGE = 'addmtoolbox', sd, theta, drift, non_decision_time, maxdur, update, fixation_model, nr_reps, timestep)
}

#' Simulate aDDM process by unique trial condition (>2 items)
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title Simulate aDDM process by unique trial condition (>2 items)
#' \code{aevacc_by_condition()}
#' @return vector that stores decisions and rts for each simulation run
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta (attentional bias) used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur maximum duration in ms that the process is allowed to simulate
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixpos Vector that stores the locations for a supplied fixed fixation pathway
#' @param fixdur Vector that stores the fixation durations for a supplied fixed fixation pathway
#' @param fixdursamples Vector from which fixation duration can be sampled once supplied fixations run out
#' @param fixation_model a user supplied fixation model that will be utilized to supply fixation locations and potentially fixation durations
#' @export
aevacc_by_condition <- function(sd, theta, drift, non_decision_time, maxdur, update, fixation_model, nr_reps, timestep) {
    .Call('addmtoolbox_aevacc_by_condition', PACKAGE = 'addmtoolbox', sd, theta, drift, non_decision_time, maxdur, update, fixation_model, nr_reps, timestep)
}

#' Simulate aDDM process by unique trial condition (>2 items, allow memory effects)
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title Simulate aDDM process by unique trial condition (>2 items, allow memory effects)
#' \code{aevacc_by_condition_memnoise()}
#' @return vector that stores decisions and rts for each simulation run
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta (attentional bias) used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur maximum duration in ms that the process is allowed to simulate
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixpos Vector that stores the locations for a supplied fixed fixation pathway
#' @param fixdur Vector that stores the fixation durations for a supplied fixed fixation pathway
#' @param fixdursamples Vector from which fixation duration can be sampled once supplied fixations run out
#' @param fixation_model a user supplied fixation model that will be utilized to supply fixation locations and potentially fixation durations
#' @param items_seen_bias Numeric Variable storing the relative amount of drift that unseen items receive
#' @param items_seen_noise_bias Numeric Variable storing the relative noise sd that unseen items receive
#' @export
aevacc_by_condition_memnoise <- function(sd, theta, drift, non_decision_time, items_seen_bias, items_seen_noise_bias, maxdur, update, fixation_model, nr_reps, timestep) {
    .Call('addmtoolbox_aevacc_by_condition_memnoise', PACKAGE = 'addmtoolbox', sd, theta, drift, non_decision_time, items_seen_bias, items_seen_noise_bias, maxdur, update, fixation_model, nr_reps, timestep)
}

#' Simulate aDDM process by unique trial (>2 items)
#' \code{aevacc_by_trial()}
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title Simulate aDDM process by unique trial (>2 items)
#' @return Returns a numeric variable that provides a success count (runs that predicted a reaction time in the correct rt-bin and simultaneously the correct decision)
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta (attentional bias) used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur numeric variable that supplies the maximum reaction time considered a success in simulations
#' @param mindur numeric variable that supplies the minimum reaction time considered a succes in simulations
#' @param cur_decision numeric variable that provides the empirical decision taken in trial
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixpos Vector that stores the locations for a supplied fixed fixation pathway
#' @param fixdur Vector that stores the fixation durations for a supplied fixed fixation pathway
#' @export
aevacc_by_trial <- function(nr_reps, maxdur, mindur, cur_decision, sd, theta, drift, non_decision_time, timestep, update, fixpos, fixdur) {
    .Call('addmtoolbox_aevacc_by_trial', PACKAGE = 'addmtoolbox', nr_reps, maxdur, mindur, cur_decision, sd, theta, drift, non_decision_time, timestep, update, fixpos, fixdur)
}

#' Simulate aDDM process by unique trial (>2 items, allow memory effects)
#' \code{aevacc_by_trial_memnoise}
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title Simulate aDDM process by unique trial (>2 items, allow memory effects)
#' @return numeric variable that provides a success count (runs that predicted a reaction time in the correct rt-bin and simultaneously the correct decision)
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta (attentional bias) used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur numeric variable that supplies the maximum reaction time considered a success in simulations
#' @param mindur numeric variable that supplies the minimum reaction time considered a succes in simulations
#' @param cur_decision numeric variable that provides the empirical decision taken in trial
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixpos Vector that stores the locations for a supplied fixed fixation pathway
#' @param fixdur Vector that stores the fixation durations for a supplied fixed fixation pathway
#' @param items_seen_bias Numeric Variable storing the relative amount of drift that unseen items receive
#' @param items_seen_noise_bias Numeric Variable storing the relative noise sd that unseen items receive
#' @export
aevacc_by_trial_memnoise <- function(sd, theta, drift, non_decision_time, items_seen_bias, items_seen_noise_bias, maxdur, mindur, cur_decision, update, fixpos, fixdur, nr_reps, timestep) {
    .Call('addmtoolbox_aevacc_by_trial_memnoise', PACKAGE = 'addmtoolbox', sd, theta, drift, non_decision_time, items_seen_bias, items_seen_noise_bias, maxdur, mindur, cur_decision, update, fixpos, fixdur, nr_reps, timestep)
}

#' Simulate aDDM process (>2 items, allow memory effects) for detailed model output
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title Simulate aDDM process (>2 items, allow memory effects) for detailed model output
#' \code{aevacc_full_output_memnoise()}
#' @return vector that stores detailed output by simulation run
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta (attentional bias) used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur maximum duration in ms that the process is allowed to simulate
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixation_model a user supplied fixation model that will be utilized to supply fixation locations and potentially fixation durations
#' @param items_seen_bias Numeric Variable storing the relative amount of drift that unseen items receive
#' @param items_seen_noise_bias Numeric Variable storing the relative noise sd that unseen items receive
#' @export
aevacc_full_output_memnoise <- function(sd, theta, drift, non_decision_time, items_seen_bias, items_seen_noise_bias, maxdur, update, fixation_model, nr_reps, timestep) {
    .Call('addmtoolbox_aevacc_full_output_memnoise', PACKAGE = 'addmtoolbox', sd, theta, drift, non_decision_time, items_seen_bias, items_seen_noise_bias, maxdur, update, fixation_model, nr_reps, timestep)
}

