# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Runs evidence accumulation function (2 item case) for one trial condition
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title evidence accumulation (2 item case)
#' \code{aevacc2_by_condition} Returns data.table with log likelihoods and corresponding parameter combinations
#' @return Returns a vector that stores decisions and rts for each simulation run
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur maximum duration in ms that the process is allowed to simulate
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixation_model a user supplied fixation model that will be utilized to supply fixation locations and potentially fixation durations
#' @export
aevacc2_by_condition <- function(sd, theta, drift, non_decision_time, timestep, nr_reps, maxdur, update, fixation_model) {
    .Call('addmtoolbox_aevacc2_by_condition', PACKAGE = 'addmtoolbox', sd, theta, drift, non_decision_time, timestep, nr_reps, maxdur, update, fixation_model)
}

#' Runs evidence accumulation function (2 item case) for one trial condition
#' \code{aevacc2_by_trial}
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title evidence accumulation (2 item case) by trial
#' @return Returns a numeric variable that provides a success count (runs that predicted a reaction time in the correct rt-bin and simultaneously the correct decision)
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur numeric variable that supplies the maximum reaction time considered a success in simulations
#' @param mindur numeric variable that supplies the minimum reaction time considered a succes in simulations
#' @param real_decision numeric variable that provides the empirical decision taken in trial
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixpos Vector that stores the locations for a supplied fixed fixation pathway
#' @param fixdur Vector that stores the fixation durations for a supplied fixed fixation pathway
#' @export
aevacc2_by_trial <- function(nr_reps, maxdur, mindur, real_decision, sd, theta, drift, non_decision_time, timestep, update, fixpos, fixdur) {
    .Call('addmtoolbox_aevacc2_by_trial', PACKAGE = 'addmtoolbox', nr_reps, maxdur, mindur, real_decision, sd, theta, drift, non_decision_time, timestep, update, fixpos, fixdur)
}

#' Runs evidence accumulation function (item general case) for one trial condition
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title Evidence accumulation by condition (item general)
#' \code{aevacc_by_condition}
#' @return Returns a vector that stores decisions and rts for each simulation run
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur maximum duration in ms that the process is allowed to simulate
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixpos Vector that stores the locations for a supplied fixed fixation pathway
#' @param fixdur Vector that stores the fixation durations for a supplied fixed fixation pathway
#' @param fixdursamples Vector from which fixation duration can be sampled once supplied fixations run out
#' @param fixation_model a user supplied fixation model that will be utilized to supply fixation locations and potentially fixation durations
#' @export
aevacc_by_condition <- function(sd, theta, drift, non_decision_time, timestep, nr_reps, maxdur, update, fixpos, fixdur, fixdursamples, fixation_model) {
    .Call('addmtoolbox_aevacc_by_condition', PACKAGE = 'addmtoolbox', sd, theta, drift, non_decision_time, timestep, nr_reps, maxdur, update, fixpos, fixdur, fixdursamples, fixation_model)
}

#' Runs evidence accumulation function (item general case) for one trial condition. Flexible version allowing for memory effects. It is possible to allow scale drift rate and noise according to whether an item has been seen.
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title Flexible Evidence accumulation by condition (item general)
#' \code{aevacc_by_condition_memnoise}
#' @return Returns a vector that stores decisions and rts for each simulation run
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur maximum duration in ms that the process is allowed to simulate
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixpos Vector that stores the locations for a supplied fixed fixation pathway
#' @param fixdur Vector that stores the fixation durations for a supplied fixed fixation pathway
#' @param fixdursamples Vector from which fixation duration can be sampled once supplied fixations run out
#' @param fixation_model a user supplied fixation model that will be utilized to supply fixation locations and potentially fixation durations
#' @export
aevacc_by_condition_memnoise <- function(sd, theta, drift, non_decision_time, timestep, nr_reps, maxdur, update, fixpos, fixdur, fixdursamples, fixation_model) {
    .Call('addmtoolbox_aevacc_by_condition_memnoise', PACKAGE = 'addmtoolbox', sd, theta, drift, non_decision_time, timestep, nr_reps, maxdur, update, fixpos, fixdur, fixdursamples, fixation_model)
}

#' Runs evidence accumulation for one trial (item general case).
#' \code{aevacc_by_trial} Returns success counts for model simulation
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title evidence accumulation (2 item case) by trial
#' @return Returns a numeric variable that provides a success count (runs that predicted a reaction time in the correct rt-bin and simultaneously the correct decision)
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur numeric variable that supplies the maximum reaction time considered a success in simulations
#' @param mindur numeric variable that supplies the minimum reaction time considered a succes in simulations
#' @param cur_decision numeric variable that provides the empirical decision taken in trial
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixpos Vector that stores the locations for a supplied fixed fixation pathway
#' @param fixdur Vector that stores the fixation durations for a supplied fixed fixation pathway
#' @export
aevacc_by_trial <- function(nr_reps, maxdur, mindur, cur_decision, sd, theta, drift, non_decision_time, timestep, update, fixpos, fixdur) {
    .Call('addmtoolbox_aevacc_by_trial', PACKAGE = 'addmtoolbox', nr_reps, maxdur, mindur, cur_decision, sd, theta, drift, non_decision_time, timestep, update, fixpos, fixdur)
}

#' Runs evidence accumulation for one trial (item general case). Flexible version allowing for memory effects.
#' \code{aevacc_by_trial_memnoise} Returns success counts for model simulation
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title Flexible evidence accumulation (item general) allowing for memory effects
#' @return Returns a numeric variable that provides a success count (runs that predicted a reaction time in the correct rt-bin and simultaneously the correct decision)
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur numeric variable that supplies the maximum reaction time considered a success in simulations
#' @param mindur numeric variable that supplies the minimum reaction time considered a succes in simulations
#' @param cur_decision numeric variable that provides the empirical decision taken in trial
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixpos Vector that stores the locations for a supplied fixed fixation pathway
#' @param fixdur Vector that stores the fixation durations for a supplied fixed fixation pathway
#' @export
aevacc_by_trial_memnoise <- function(nr_reps, maxdur, mindur, cur_decision, sd, theta, drift, non_decision_time, timestep, update, fixpos, fixdur) {
    .Call('addmtoolbox_aevacc_by_trial_memnoise', PACKAGE = 'addmtoolbox', nr_reps, maxdur, mindur, cur_decision, sd, theta, drift, non_decision_time, timestep, update, fixpos, fixdur)
}

#' Runs evidence accumulation function (item general case) for one trial, and returns detailed model output
#' @author Alexander Fengler, \email{alexanderfengler@@gmx.de}
#' @title Evidence accumulation by condition (item general) with detailed output
#' \code{aevacc_full_output_memnoise}
#' @return Returns a vector that stores detailed output by simulation run
#' @param sd standard deviation used for drift diffusion process
#' @param theta theta used for drift diffusion process
#' @param drift drift-rate used for drift diffusion process
#' @param non_decision_time non decision time used for drift diffusion process
#' @param timestep timestep in ms associated with each step in the drift diffusion process
#' @param nr_reps number of repitions (simulation runs)
#' @param maxdur maximum duration in ms that the process is allowed to simulate
#' @param update Vector that stores the item valuations for the trial conditon simulated
#' @param fixation_model a user supplied fixation model that will be utilized to supply fixation locations and potentially fixation durations
#' @export
aevacc_full_output_memnoise <- function(sd, theta, drift, non_decision_time, timestep, nr_reps, maxdur, update, fixation_model) {
    .Call('addmtoolbox_aevacc_full_output_memnoise', PACKAGE = 'addmtoolbox', sd, theta, drift, non_decision_time, timestep, nr_reps, maxdur, update, fixation_model)
}

